repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 'v2.0.1'
  hooks:
  - id: autopep8

- repo: https://github.com/python-poetry/poetry
  rev: '1.3.2'
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
